import 'dart:math';

import 'package:new_football/core/models/assigned_role.dart';
import 'package:new_football/core/models/contract.dart';
import 'package:new_football/core/models/development.dart';
import 'package:new_football/core/models/draft_models.dart';
import 'package:new_football/core/models/enums.dart';
import 'package:new_football/core/models/league_state.dart';
import 'package:new_football/core/models/player.dart';
import 'package:new_football/core/models/field_player_attributes.dart';
import 'package:new_football/core/models/goalkeeper_attributes.dart';
import 'package:new_football/core/models/player_attributes.dart';
import 'package:new_football/core/models/standing.dart';
import 'package:new_football/core/models/team.dart';

class SeedDataGenerator {
  SeedDataGenerator({Random? random}) : _random = random ?? Random();

  final Random _random;

  static const _eastCities = [
    ('Warsaw', 'Poland FC'),
    ('Paris', 'Paris SC'),
    ('Marseille', 'Marseille FC'),
    ('Madrid', 'Madrid United'),
    ('Barcelona', 'Barcelona Athletic'),
    ('London', 'London City'),
    ('Manchester', 'Manchester United'),
    ('Liverpool', 'Liverpool SC'),
    ('Berlin', 'Berlin FC'),
    ('Brussels', 'Brussels FC'),
    ('Amsterdam', 'Amsterdam City'),
    ('Lisbon', 'Lisbon FC'),
    ('Rome', 'Rome United'),
    ('Milan', 'Milan SC'),
    ('Neapol', 'Neapol Athletic'),
  ];

  static const _westCities = [
    ('Sao Paulo', 'Sao Paulo FC'),
    ('Rio de Janeiro', 'Rio Athletic'),
    ('Buenos Aires', 'Buenos Aires City'),
    ('Tokyo', 'Tokyo FC'),
    ('New York City', 'New York United'),
    ('Los Angeles', 'Los Angeles FC'),
    ('Chicago', 'Chicago Athletic'),
    ('Philadelphia', 'Philadelphia SC'),
    ('Kyoto', 'Kyoto FC'),
    ('Shanghai', 'Shanghai United'),
    ('Beijing', 'Beijing Athletic'),
    ('Mexico City', 'Mexico City SC'),
    ('Casablanca', 'Casablanca FC'),
    ('Cairo', 'Cairo United'),
    ('Lagos', 'Lagos Athletic'),
  ];

  static const _namePools = <Nationality, _NamePool>{
    Nationality.poland: _NamePool(
      firstNames: [
        'Jan',
        'Piotr',
        'Krzysztof',
        'Andrzej',
        'Tomasz',
        'Paweł',
        'Michał',
        'Marcin',
        'Adam',
        'Łukasz',
        'Mateusz',
        'Jakub',
        'Kamil',
        'Szymon',
        'Grzegorz',
        'Dawid',
        'Sebastian',
        'Bartosz',
        'Rafał',
        'Artur',
        'Dominik',
        'Patryk',
        'Norbert',
        'Oskar',
        'Igor',
      ],
      lastNames: [
        'Nowak',
        'Kowalski',
        'Wiśniewski',
        'Wójcik',
        'Kowalczyk',
        'Kamiński',
        'Lewandowski',
        'Zieliński',
        'Szymański',
        'Woźniak',
        'Dąbrowski',
        'Kozłowski',
        'Jankowski',
        'Mazur',
        'Krawczyk',
        'Piotrowski',
        'Grabowski',
        'Nowicki',
        'Pawłowski',
        'Michalski',
        'Król',
        'Wieczorek',
        'Wróbel',
        'Dudek',
        'Olszewski',
      ],
    ),
    Nationality.brazil: _NamePool(
      firstNames: [
        'Joao',
        'Gabriel',
        'Lucas',
        'Matheus',
        'Pedro',
        'Gustavo',
        'Felipe',
        'Rafael',
        'Bruno',
        'Diego',
        'Andre',
        'Carlos',
        'Thiago',
        'Vinicius',
        'Leonardo',
        'Eduardo',
        'Marcelo',
        'Caio',
        'Igor',
        'Rodrigo',
        'Daniel',
        'Renato',
        'Alex',
        'Samuel',
        'Vitor',
      ],
      lastNames: [
        'Silva',
        'Santos',
        'Oliveira',
        'Souza',
        'Rodrigues',
        'Ferreira',
        'Alves',
        'Pereira',
        'Lima',
        'Gomes',
        'Costa',
        'Ribeiro',
        'Martins',
        'Carvalho',
        'Araujo',
        'Melo',
        'Barbosa',
        'Rocha',
        'Dias',
        'Teixeira',
        'Moreira',
        'Correia',
        'Monteiro',
        'Cardoso',
        'Batista',
      ],
    ),
    Nationality.france: _NamePool(
      firstNames: [
        'Jean',
        'Pierre',
        'Louis',
        'Lucas',
        'Hugo',
        'Gabriel',
        'Arthur',
        'Jules',
        'Leo',
        'Nathan',
        'Ethan',
        'Paul',
        'Thomas',
        'Antoine',
        'Maxime',
        'Alexandre',
        'Mathieu',
        'Nicolas',
        'Julien',
        'Baptiste',
        'Theo',
        'Adrien',
        'Romain',
        'Florian',
        'Quentin',
      ],
      lastNames: [
        'Martin',
        'Bernard',
        'Dubois',
        'Thomas',
        'Robert',
        'Richard',
        'Petit',
        'Durand',
        'Leroy',
        'Moreau',
        'Simon',
        'Laurent',
        'Lefebvre',
        'Michel',
        'Garcia',
        'David',
        'Bertrand',
        'Roux',
        'Vincent',
        'Fournier',
        'Morel',
        'Girard',
        'Andre',
        'Mercier',
        'Dupont',
      ],
    ),
    Nationality.spain: _NamePool(
      firstNames: [
        'Antonio',
        'Jose',
        'Manuel',
        'Francisco',
        'David',
        'Juan',
        'Javier',
        'Daniel',
        'Carlos',
        'Alejandro',
        'Miguel',
        'Rafael',
        'Pedro',
        'Pablo',
        'Sergio',
        'Alvaro',
        'Adrian',
        'Diego',
        'Mario',
        'Victor',
        'Luis',
        'Fernando',
        'Angel',
        'Hector',
        'Ivan',
      ],
      lastNames: [
        'Garcia',
        'Martinez',
        'Lopez',
        'Sanchez',
        'Perez',
        'Gonzalez',
        'Rodriguez',
        'Fernandez',
        'Gomez',
        'Diaz',
        'Alvarez',
        'Moreno',
        'Munoz',
        'Romero',
        'Alonso',
        'Gutierrez',
        'Navarro',
        'Torres',
        'Dominguez',
        'Vazquez',
        'Ramos',
        'Gil',
        'Serrano',
        'Blanco',
        'Molina',
      ],
    ),
    Nationality.england: _NamePool(
      firstNames: [
        'James',
        'Oliver',
        'Jack',
        'Harry',
        'George',
        'Noah',
        'Charlie',
        'Jacob',
        'Thomas',
        'Oscar',
        'William',
        'Henry',
        'Leo',
        'Alfie',
        'Joshua',
        'Freddie',
        'Archie',
        'Ethan',
        'Isaac',
        'Alexander',
        'Joseph',
        'Edward',
        'Samuel',
        'Max',
        'Daniel',
      ],
      lastNames: [
        'Smith',
        'Jones',
        'Taylor',
        'Brown',
        'Williams',
        'Wilson',
        'Johnson',
        'Davies',
        'Patel',
        'Wright',
        'Walker',
        'White',
        'Edwards',
        'Green',
        'Hall',
        'Thomas',
        'Clarke',
        'Jackson',
        'Wood',
        'Harris',
        'Martin',
        'Cooper',
        'Hill',
        'Ward',
        'Turner',
      ],
    ),
    Nationality.germany: _NamePool(
      firstNames: [
        'Lukas',
        'Leon',
        'Finn',
        'Paul',
        'Jonas',
        'Elias',
        'Noah',
        'Felix',
        'Maximilian',
        'Julian',
        'Tim',
        'Moritz',
        'Niklas',
        'David',
        'Alexander',
        'Simon',
        'Philipp',
        'Ben',
        'Tobias',
        'Johannes',
        'Fabian',
        'Erik',
        'Marcel',
        'Daniel',
        'Jan',
      ],
      lastNames: [
        'Muller',
        'Schmidt',
        'Schneider',
        'Fischer',
        'Weber',
        'Meyer',
        'Wagner',
        'Becker',
        'Schulz',
        'Hoffmann',
        'Schaffer',
        'Koch',
        'Bauer',
        'Richter',
        'Klein',
        'Wolf',
        'Schroder',
        'Neumann',
        'Schwarz',
        'Zimmermann',
        'Braun',
        'Kruger',
        'Hofmann',
        'Hartmann',
        'Lange',
      ],
    ),
    Nationality.argentina: _NamePool(
      firstNames: [
        'Juan',
        'Santiago',
        'Mateo',
        'Nicolas',
        'Tomas',
        'Lucas',
        'Benjamin',
        'Facundo',
        'Franco',
        'Agustin',
        'Martin',
        'Ignacio',
        'Federico',
        'Gonzalo',
        'Diego',
        'Julian',
        'Marcos',
        'Emiliano',
        'Alejandro',
        'Maximiliano',
        'Leonardo',
        'Adrian',
        'Pedro',
        'Ezequiel',
        'Matias',
      ],
      lastNames: [
        'Gonzalez',
        'Rodriguez',
        'Gomez',
        'Fernandez',
        'Lopez',
        'Martinez',
        'Perez',
        'Sanchez',
        'Romero',
        'Diaz',
        'Alvarez',
        'Torres',
        'Ruiz',
        'Ramirez',
        'Flores',
        'Acosta',
        'Benitez',
        'Medina',
        'Herrera',
        'Suarez',
        'Castro',
        'Vega',
        'Rojas',
        'Molina',
        'Silva',
      ],
    ),
    Nationality.portugal: _NamePool(
      firstNames: [
        'Joao',
        'Diogo',
        'Tiago',
        'Miguel',
        'Andre',
        'Pedro',
        'Rui',
        'Luis',
        'Goncalo',
        'Afonso',
        'Tomas',
        'Rodrigo',
        'Daniel',
        'Francisco',
        'Ricardo',
        'Bruno',
        'Jose',
        'Nuno',
        'Vasco',
        'Henrique',
        'Duarte',
        'Leandro',
        'Marco',
        'Simao',
        'Filipe',
      ],
      lastNames: [
        'Silva',
        'Santos',
        'Ferreira',
        'Pereira',
        'Oliveira',
        'Costa',
        'Rodrigues',
        'Martins',
        'Jesus',
        'Sousa',
        'Fernandes',
        'Goncalves',
        'Gomes',
        'Lopes',
        'Marques',
        'Alves',
        'Almeida',
        'Ribeiro',
        'Pinto',
        'Carvalho',
        'Teixeira',
        'Moreira',
        'Correia',
        'Mendes',
        'Nunes',
      ],
    ),
    Nationality.italy: _NamePool(
      firstNames: [
        'Luca',
        'Marco',
        'Matteo',
        'Alessandro',
        'Francesco',
        'Andrea',
        'Davide',
        'Giuseppe',
        'Antonio',
        'Stefano',
        'Simone',
        'Lorenzo',
        'Federico',
        'Gabriele',
        'Riccardo',
        'Leonardo',
        'Salvatore',
        'Paolo',
        'Roberto',
        'Emanuele',
        'Nicolo',
        'Daniele',
        'Filippo',
        'Enrico',
        'Cristian',
      ],
      lastNames: [
        'Rossi',
        'Russo',
        'Ferrari',
        'Esposito',
        'Bianchi',
        'Romano',
        'Colombo',
        'Ricci',
        'Marino',
        'Greco',
        'Bruno',
        'Gallo',
        'Conti',
        'De Luca',
        'Mancini',
        'Costa',
        'Giordano',
        'Rizzo',
        'Lombardi',
        'Moretti',
        'Barbieri',
        'Fontana',
        'Santoro',
        'Mariani',
        'Rinaldi',
      ],
    ),
    Nationality.netherlands: _NamePool(
      firstNames: [
        'Daan',
        'Sem',
        'Milan',
        'Luuk',
        'Levi',
        'Finn',
        'Noah',
        'Thijs',
        'Bram',
        'Lars',
        'Jesse',
        'Max',
        'Thomas',
        'Julian',
        'Ruben',
        'Niels',
        'Jasper',
        'Tim',
        'Stijn',
        'Mees',
        'Timo',
        'Sven',
        'Koen',
        'Nick',
        'Cas',
      ],
      lastNames: [
        'De Jong',
        'Jansen',
        'De Vries',
        'Van den Berg',
        'Van Dijk',
        'Bakker',
        'Janssen',
        'Visser',
        'Smit',
        'Meijer',
        'De Boer',
        'Mulder',
        'De Groot',
        'Bos',
        'Vos',
        'Peters',
        'Hendriks',
        'Van Leeuwen',
        'Dekker',
        'Brouwer',
        'De Wit',
        'Dijkstra',
        'Smits',
        'Kuiper',
        'Schouten',
      ],
    ),
    Nationality.belgium: _NamePool(
      firstNames: [
        'Louis',
        'Noah',
        'Liam',
        'Lucas',
        'Jules',
        'Arthur',
        'Victor',
        'Leon',
        'Nathan',
        'Adam',
        'Milan',
        'Mathis',
        'Julien',
        'Thomas',
        'Maxime',
        'Alexandre',
        'Simon',
        'Hugo',
        'Antoine',
        'Elias',
        'Florian',
        'Brent',
        'Seppe',
        'Jens',
        'Robin',
      ],
      lastNames: [
        'Peeters',
        'Janssens',
        'Maes',
        'Jacobs',
        'Mertens',
        'Willems',
        'Claes',
        'Goossens',
        'Wouters',
        'De Smet',
        'Dubois',
        'Lambert',
        'Martens',
        'Vermeulen',
        'Leroy',
        'Dumont',
        'Simon',
        'Leclercq',
        'Hubert',
        'Bogaerts',
        'Dierckx',
        'Van Damme',
        'De Wolf',
        'Vandenberghe',
        'Denis',
      ],
    ),
    Nationality.croatia: _NamePool(
      firstNames: [
        'Ivan',
        'Marko',
        'Josip',
        'Luka',
        'Matej',
        'Filip',
        'Ante',
        'Petar',
        'Mario',
        'Tomislav',
        'Nikola',
        'Domagoj',
        'Karlo',
        'Stjepan',
        'Antonio',
        'Dario',
        'Kristijan',
        'Marin',
        'Bruno',
        'Fran',
        'Tin',
        'Lovro',
        'Andrej',
        'Igor',
        'Hrvoje',
      ],
      lastNames: [
        'Horvat',
        'Kovac',
        'Babic',
        'Maric',
        'Jukic',
        'Novak',
        'Knezevic',
        'Vukovic',
        'Kovacevic',
        'Markovic',
        'Petrovic',
        'Tomic',
        'Bozic',
        'Pavic',
        'Matic',
        'Mikulic',
        'Peric',
        'Grgic',
        'Juric',
        'Vidovic',
        'Pilipovic',
        'Lucic',
        'Mandic',
        'Radic',
        'Sesar',
      ],
    ),
    Nationality.nigeria: _NamePool(
      firstNames: [
        'Chinedu',
        'Emeka',
        'Oluwaseun',
        'Ibrahim',
        'Musa',
        'Tunde',
        'Seyi',
        'Kunle',
        'Uche',
        'Nnamdi',
        'Chukwuemeka',
        'Ayo',
        'Femi',
        'Segun',
        'Kelechi',
        'Obinna',
        'Samuel',
        'David',
        'Michael',
        'Emmanuel',
        'Daniel',
        'Yusuf',
        'Haruna',
        'Isaac',
        'John',
      ],
      lastNames: [
        'Okafor',
        'Balogun',
        'Adebayo',
        'Okoro',
        'Mohammed',
        'Ibrahim',
        'Bello',
        'Abubakar',
        'Ogunleye',
        'Nwosu',
        'Eze',
        'Adeyemi',
        'Onyeka',
        'Chukwu',
        'Lawal',
        'Usman',
        'Afolabi',
        'Okeke',
        'Musa',
        'Ojo',
        'Yusuf',
        'Danjuma',
        'Sani',
        'Aliyu',
        'Nnamani',
      ],
    ),
    Nationality.senegal: _NamePool(
      firstNames: [
        'Mamadou',
        'Ousmane',
        'Ibrahima',
        'Cheikh',
        'Moussa',
        'Amadou',
        'Pape',
        'Alioune',
        'Abdoulaye',
        'Babacar',
        'Modou',
        'Seydou',
        'Serigne',
        'Mouhamed',
        'Daouda',
        'Souleymane',
        'Malick',
        'Bamba',
        'Lamine',
        'Issa',
        'Samba',
        'Omar',
        'Alpha',
        'Djibril',
        'Moustapha',
      ],
      lastNames: [
        'Ndiaye',
        'Diop',
        'Fall',
        'Sarr',
        'Ndiour',
        'Ba',
        'Diallo',
        'Sow',
        'Seck',
        'Faye',
        'Gueye',
        'Camara',
        'Cisse',
        'Sy',
        'Sall',
        'Kane',
        'Mbaye',
        'Diagne',
        'Ka',
        'Dieng',
        'Ndour',
        'Thiam',
        'Lo',
        'Beye',
        'Samb',
      ],
    ),
    Nationality.japan: _NamePool(
      firstNames: [
        'Haruto',
        'Yuto',
        'Sota',
        'Yuki',
        'Hayato',
        'Ryota',
        'Kaito',
        'Ren',
        'Takumi',
        'Daiki',
        'Sho',
        'Kenta',
        'Yuma',
        'Riku',
        'Tsubasa',
        'Keita',
        'Naoki',
        'Shota',
        'Koki',
        'Takeru',
        'Hiroto',
        'Itsuki',
        'Sora',
        'Hinata',
        'Minato',
      ],
      lastNames: [
        'Sato',
        'Suzuki',
        'Takahashi',
        'Tanaka',
        'Watanabe',
        'Ito',
        'Yamamoto',
        'Nakamura',
        'Kobayashi',
        'Kato',
        'Yoshida',
        'Yamada',
        'Sasaki',
        'Yamaguchi',
        'Matsumoto',
        'Inoue',
        'Kimura',
        'Hayashi',
        'Shimizu',
        'Yamazaki',
        'Mori',
        'Abe',
        'Ikeda',
        'Hashimoto',
        'Ishikawa',
      ],
    ),
    Nationality.usa: _NamePool(
      firstNames: [
        'James',
        'Michael',
        'John',
        'Robert',
        'David',
        'William',
        'Joseph',
        'Daniel',
        'Matthew',
        'Anthony',
        'Christopher',
        'Andrew',
        'Joshua',
        'Ryan',
        'Nicholas',
        'Jacob',
        'Tyler',
        'Brandon',
        'Justin',
        'Alexander',
        'Ethan',
        'Noah',
        'Liam',
        'Logan',
        'Benjamin',
      ],
      lastNames: [
        'Smith',
        'Johnson',
        'Williams',
        'Brown',
        'Jones',
        'Garcia',
        'Miller',
        'Davis',
        'Rodriguez',
        'Martinez',
        'Hernandez',
        'Lopez',
        'Gonzalez',
        'Wilson',
        'Anderson',
        'Thomas',
        'Taylor',
        'Moore',
        'Jackson',
        'Martin',
        'Lee',
        'Perez',
        'Thompson',
        'White',
        'Harris',
      ],
    ),
    Nationality.mexico: _NamePool(
      firstNames: [
        'Jose',
        'Juan',
        'Luis',
        'Carlos',
        'Jorge',
        'Miguel',
        'Angel',
        'Alejandro',
        'Fernando',
        'Francisco',
        'Daniel',
        'Antonio',
        'Jesus',
        'Manuel',
        'Pedro',
        'Ricardo',
        'Diego',
        'Sergio',
        'Javier',
        'Adrian',
        'Rafael',
        'Victor',
        'Eduardo',
        'Oscar',
        'Emiliano',
      ],
      lastNames: [
        'Hernandez',
        'Garcia',
        'Martinez',
        'Lopez',
        'Gonzalez',
        'Perez',
        'Rodriguez',
        'Sanchez',
        'Ramirez',
        'Cruz',
        'Flores',
        'Gomez',
        'Morales',
        'Vazquez',
        'Reyes',
        'Jimenez',
        'Torres',
        'Diaz',
        'Gutierrez',
        'Ruiz',
        'Mendoza',
        'Aguilar',
        'Castillo',
        'Ortiz',
        'Moreno',
      ],
    ),
    Nationality.morocco: _NamePool(
      firstNames: [
        'Mohamed',
        'Youssef',
        'Ahmed',
        'Omar',
        'Hamza',
        'Ayoub',
        'Mehdi',
        'Zakaria',
        'Anas',
        'Soufiane',
        'Rachid',
        'Karim',
        'Amine',
        'Bilal',
        'Khalid',
        'Mustapha',
        'Nabil',
        'Said',
        'Othmane',
        'Reda',
        'Imad',
        'Hicham',
        'Walid',
        'Tarik',
        'Adil',
      ],
      lastNames: [
        'Alaoui',
        'El Amrani',
        'Bennani',
        'Tazi',
        'Idrissi',
        'Ouali',
        'Lahlou',
        'Berrada',
        'Skalli',
        'Benjelloun',
        'Amrani',
        'Fassi',
        'Karimi',
        'Rharbi',
        'Ouazzani',
        'Hassani',
        'Mansouri',
        'Mehdioui',
        'Chraibi',
        'Boukhris',
        'Tahiri',
        'Zerouali',
        'Belkadi',
        'Ait Said',
        'Kadiri',
      ],
    ),
    Nationality.colombia: _NamePool(
      firstNames: [
        'Juan',
        'Santiago',
        'Sebastian',
        'Andres',
        'David',
        'Daniel',
        'Felipe',
        'Alejandro',
        'Nicolas',
        'Miguel',
        'Jose',
        'Camilo',
        'Jhon',
        'Kevin',
        'Mateo',
        'Luis',
        'Carlos',
        'Cristian',
        'Javier',
        'Diego',
        'Julian',
        'Esteban',
        'Brayan',
        'Angel',
        'Emmanuel',
      ],
      lastNames: [
        'Rodriguez',
        'Gomez',
        'Gonzalez',
        'Martinez',
        'Garcia',
        'Lopez',
        'Hernandez',
        'Perez',
        'Sanchez',
        'Ramirez',
        'Torres',
        'Diaz',
        'Moreno',
        'Jimenez',
        'Ruiz',
        'Alvarez',
        'Castro',
        'Romero',
        'Herrera',
        'Vargas',
        'Gutierrez',
        'Cardenas',
        'Rojas',
        'Medina',
        'Suarez',
      ],
    ),
    Nationality.switzerland: _NamePool(
      firstNames: [
        'Luca',
        'Noah',
        'Leon',
        'Elias',
        'Finn',
        'Julian',
        'Nico',
        'Jan',
        'Tim',
        'Simon',
        'David',
        'Jonas',
        'Fabian',
        'Samuel',
        'Adrian',
        'Pascal',
        'Marco',
        'Matteo',
        'Florian',
        'Raphael',
        'Silvan',
        'Livio',
        'Tobias',
        'Dominik',
        'Roman',
      ],
      lastNames: [
        'Muller',
        'Meier',
        'Schmid',
        'Keller',
        'Weber',
        'Huber',
        'Meyer',
        'Steiner',
        'Fischer',
        'Brunner',
        'Baumann',
        'Gerber',
        'Frei',
        'Widmer',
        'Kunz',
        'Schneider',
        'Bucher',
        'Roth',
        'Ammann',
        'Zimmermann',
        'Sutter',
        'Graf',
        'Buhler',
        'Gisler',
        'Marti',
      ],
    ),
    Nationality.uruguay: _NamePool(
      firstNames: [
        'Santiago',
        'Mateo',
        'Benjamin',
        'Martin',
        'Nicolas',
        'Juan',
        'Facundo',
        'Franco',
        'Tomas',
        'Agustin',
        'Lucas',
        'Joaquin',
        'Emiliano',
        'Thiago',
        'Valentin',
        'Ignacio',
        'Bautista',
        'Maximiliano',
        'Matias',
        'Federico',
        'Alejandro',
        'Diego',
        'Gonzalo',
        'Leandro',
        'Bruno',
      ],
      lastNames: [
        'Rodriguez',
        'Gonzalez',
        'Martinez',
        'Fernandez',
        'Lopez',
        'Perez',
        'Gomez',
        'Silva',
        'Sosa',
        'Pereira',
        'Diaz',
        'Alvarez',
        'Torres',
        'Vazquez',
        'Suarez',
        'Acosta',
        'Romero',
        'Mendez',
        'Ruiz',
        'Morales',
        'Cabrera',
        'Benitez',
        'Castro',
        'Ramos',
        'Gutierrez',
      ],
    ),
    Nationality.egypt: _NamePool(
      firstNames: [
        'Mohamed',
        'Ahmed',
        'Mahmoud',
        'Mostafa',
        'Omar',
        'Youssef',
        'Khaled',
        'Amr',
        'Tamer',
        'Karim',
        'Hossam',
        'Ibrahim',
        'Ayman',
        'Sherif',
        'Wael',
        'Mina',
        'Alaa',
        'Islam',
        'Hesham',
        'Samir',
        'Nader',
        'Emad',
        'Adel',
        'Ramy',
        'Marwan',
      ],
      lastNames: [
        'Mohamed',
        'Ahmed',
        'Hassan',
        'Mahmoud',
        'Ali',
        'Ibrahim',
        'Mostafa',
        'Abdelrahman',
        'Abdallah',
        'Khalil',
        'Farag',
        'Naguib',
        'Saad',
        'Shahin',
        'Fawzy',
        'Gamal',
        'Youssef',
        'Tawfik',
        'Hamdy',
        'Ezzat',
        'Soliman',
        'Morsi',
        'Zaki',
        'Rizk',
        'Shalaby',
      ],
    ),
    Nationality.china: _NamePool(
      firstNames: [
        'Wei',
        'Jun',
        'Ming',
        'Hao',
        'Lei',
        'Tao',
        'Jie',
        'Bin',
        'Chen',
        'Yang',
        'Feng',
        'Guo',
        'Hui',
        'Jian',
        'Yong',
        'Peng',
        'Xiang',
        'Bo',
        'Rui',
        'Zheng',
        'Xuan',
        'Yu',
        'Zhi',
        'Kai',
        'Liu',
      ],
      lastNames: [
        'Wang',
        'Li',
        'Zhang',
        'Liu',
        'Chen',
        'Yang',
        'Huang',
        'Zhao',
        'Wu',
        'Zhou',
        'Xu',
        'Sun',
        'Ma',
        'Zhu',
        'Hu',
        'Guo',
        'He',
        'Gao',
        'Lin',
        'Luo',
        'Zheng',
        'Xie',
        'Tang',
        'Song',
        'Deng',
      ],
    ),
  };

  LeagueState generateLeague({
    int year = 2026,
    String? playerTeamId,
    int? seed,
  }) {
    final rng = seed != null ? Random(seed) : Random();
    final teams = <Team>[];

    for (var i = 0; i < _eastCities.length; i++) {
      final (city, name) = _eastCities[i];
      teams.add(
        _generateTeam(
          city: city,
          name: name,
          conference: Conference.east,
          index: i,
          rng: rng,
          isPlayer: playerTeamId != null && i == 0,
        ),
      );
    }

    for (var i = 0; i < _westCities.length; i++) {
      final (city, name) = _westCities[i];
      teams.add(
        _generateTeam(
          city: city,
          name: name,
          conference: Conference.west,
          index: i + 15,
          rng: rng,
          isPlayer: false,
        ),
      );
    }

    if (playerTeamId != null) {
      final idx = teams.indexWhere((t) => t.id == playerTeamId);
      if (idx >= 0) {
        teams[idx] = teams[idx].copyWith(ai: null);
      }
    } else {
      teams[0] = teams[0].copyWith(ai: null);
    }

    final actualPlayerTeamId = playerTeamId ?? teams[0].id;

    final standings = [
      ConferenceStandings(
        conference: Conference.east,
        standings: teams
            .where((t) => t.conference == Conference.east)
            .map((t) => Standing(teamId: t.id))
            .toList(),
      ),
      ConferenceStandings(
        conference: Conference.west,
        standings: teams
            .where((t) => t.conference == Conference.west)
            .map((t) => Standing(teamId: t.id))
            .toList(),
      ),
    ];

    return LeagueState(
      teams: teams,
      currentSeason: Season(year: year, standings: standings),
      playerTeamId: actualPlayerTeamId,
    );
  }

  Team _generateTeam({
    required String city,
    required String name,
    required Conference conference,
    required int index,
    required Random rng,
    required bool isPlayer,
  }) {
    final teamId = 'team_${conference.name}_$index';
    final roster = _generateRoster(
      teamId,
      rng,
      strengthBase: 55 + rng.nextInt(20),
    );

    final payroll = roster.fold<int>(0, (s, p) => s + p.contract.salary);

    return Team(
      id: teamId,
      name: name,
      city: city,
      conference: conference,
      roster: roster,
      finance: TeamFinance(totalPayroll: payroll),
      lineupPlayerIds: roster.take(11).map((p) => p.id).toList(),
      benchPlayerIds: roster.skip(11).take(7).map((p) => p.id).toList(),
      ai: isPlayer
          ? null
          : TeamAiConfig(managerProfile: ManagerProfile.values[rng.nextInt(3)]),
    );
  }

  List<Player> _generateRoster(
    String teamId,
    Random rng, {
    required int strengthBase,
  }) {
    const positions = [
      Position.gk,
      Position.gk,
      Position.cb,
      Position.cb,
      Position.cb,
      Position.lb,
      Position.rb,
      Position.cdm,
      Position.cm,
      Position.cm,
      Position.cam,
      Position.lw,
      Position.rw,
      Position.st,
      Position.st,
      Position.cb,
      Position.cm,
      Position.lw,
      Position.rw,
      Position.st,
      Position.gk,
      Position.cdm,
      Position.cam,
      Position.st,
      Position.lb,
    ];

    return positions.asMap().entries.map((entry) {
      final pos = entry.value;
      final variance = rng.nextInt(15) - 7;
      final base = (strengthBase + variance).clamp(40, 95);
      return _generatePlayer(
        teamId: teamId,
        position: pos,
        base: base,
        rng: rng,
        index: entry.key,
      );
    }).toList();
  }

  Player _generatePlayer({
    required String teamId,
    required Position position,
    required int base,
    required Random rng,
    required int index,
  }) {
    final id = '${teamId}_player_$index';
    final nationality =
        Nationality.values[rng.nextInt(Nationality.values.length)];
    final name = _generateName(rng, nationality);
    final age = 19 + rng.nextInt(17);

    final PlayerAttributes attrs;
    if (position == Position.gk) {
      attrs = PlayerAttributes.goalkeeper(
        stats: GoalkeeperAttributes(
          diving: _attr(base, rng, boost: 5),
          handling: _attr(base, rng, boost: 5),
          kicking: _attr(base, rng),
          reflexes: _attr(base, rng, boost: 5),
          speed: _attr(base, rng),
          positioning: _attr(base, rng, boost: 3),
        ),
      );
    } else {
      attrs = PlayerAttributes.outfield(
        stats: FieldPlayerAttributes(
          pace: _attr(
            base,
            rng,
            boost: position.code == 'LW' || position.code == 'RW' ? 5 : 0,
          ),
          shooting: _attr(base, rng, boost: position.code == 'ST' ? 5 : 0),
          passing: _attr(base, rng),
          dribbling: _attr(base, rng),
          defending: _attr(base, rng, boost: position.code == 'CB' ? 5 : 0),
          physicality: _attr(base, rng),
        ),
      );
    }

    final salary = (500000 + base * 400000 + rng.nextInt(500000)).clamp(
      500000,
      80000000,
    );

    final potentialStars = ((base - 50) / 10).clamp(0.5, 5.0);
    final roundedStars = (potentialStars * 2).round() / 2.0;

    final injuryProne = 1 + rng.nextInt(10);
    final determination = 1 + rng.nextInt(10);
    final heightCm = _heightCmFor(position, rng);

    return Player(
      id: id,
      name: name,
      position: position,
      nationality: nationality,
      age: age,
      attributes: attrs,
      personality: PlayerPersonality
          .values[rng.nextInt(PlayerPersonality.values.length)],
      potentialStars: roundedStars,
      heightCm: heightCm,
      contract: Contract(
        salary: salary,
        yearsRemaining: 1 + rng.nextInt(4),
        hasBirdRights: rng.nextBool(),
      ),
      state: PlayerState(
        stamina: 85 + rng.nextInt(15),
        form: 1 + rng.nextInt(10),
        role: position.defaultAssignedRole,
        seasonsWithTeam: rng.nextInt(5),
      ),
      hidden: PlayerHidden(
        injuryProne: injuryProne,
        determination: determination,
        overallProgress: (age <= 26 ? 40 + rng.nextInt(50) : rng.nextInt(30))
            .clamp(0, 99),
        growthRate: (0.7 + rng.nextDouble() * 0.8).clamp(0.0, 2.0),
        developmentOutcome: rollDevelopmentOutcome(determination, rng),
      ),
    );
  }

  int _heightCmFor(Position position, Random rng) {
    final (minH, maxH) = switch (position) {
      Position.gk => (185, 200),
      Position.cb => (180, 195),
      Position.st => (175, 193),
      Position.cdm => (175, 190),
      _ => (168, 188),
    };
    return minH + rng.nextInt(maxH - minH + 1);
  }

  int _attr(int base, Random rng, {int boost = 0}) =>
      (base + boost + rng.nextInt(10) - 5).clamp(50, 99);

  DraftClass generateDraftClass({required int year, int prospectCount = 120}) {
    final prospects = <Prospect>[];
    for (var i = 0; i < prospectCount; i++) {
      final positions = Position.values.where((p) => p != Position.gk).toList();
      if (i < 3) {
        positions.insert(0, Position.gk);
      }
      final pos = positions[_random.nextInt(positions.length)];
      final base = (90 - i * 0.8 + _random.nextInt(10) - 5).round().clamp(
        50,
        95,
      );
      final nationality =
          Nationality.values[_random.nextInt(Nationality.values.length)];
      final potentialStars = ((base - 50) / 10).clamp(0.5, 5.0);
      final roundedStars = (potentialStars * 2).round() / 2.0;

      prospects.add(
        Prospect(
          id: 'prospect_${year}_$i',
          personality: PlayerPersonality
              .values[_random.nextInt(PlayerPersonality.values.length)],
          name: _generateName(_random, nationality),
          nationality: nationality,
          position: pos,
          age: 18 + _random.nextInt(3),
          attributes: pos == Position.gk
              ? PlayerAttributes.goalkeeper(
                  stats: GoalkeeperAttributes(
                    diving: _attr(base, _random, boost: 5),
                    handling: _attr(base, _random, boost: 5),
                    kicking: _attr(base, _random),
                    reflexes: _attr(base, _random, boost: 5),
                    speed: _attr(base, _random),
                    positioning: _attr(base, _random, boost: 3),
                  ),
                )
              : PlayerAttributes.outfield(
                  stats: FieldPlayerAttributes(
                    pace: _attr(base, _random),
                    shooting: _attr(base, _random),
                    passing: _attr(base, _random),
                    dribbling: _attr(base, _random),
                    defending: _attr(base, _random),
                    physicality: _attr(base, _random),
                  ),
                ),
          scoutGrade: (base + _random.nextInt(8) - 4).clamp(30, 99),
          combineScore: (base + _random.nextInt(12) - 6).clamp(30, 99),
          potentialStars: roundedStars,
          heightCm: _heightCmFor(pos, _random),
          injuryProne: 1 + _random.nextInt(10),
          determination: 1 + _random.nextInt(10),
        ),
      );
    }
    prospects.sort((a, b) => b.scoutGrade.compareTo(a.scoutGrade));
    return DraftClass(year: year, prospects: prospects);
  }

  String _generateName(Random rng, Nationality nationality) {
    final pool = _namePools[nationality]!;
    final firstName = pool.firstNames[rng.nextInt(pool.firstNames.length)];
    final lastName = pool.lastNames[rng.nextInt(pool.lastNames.length)];
    return '$firstName $lastName';
  }
}

class _NamePool {
  const _NamePool({required this.firstNames, required this.lastNames});

  final List<String> firstNames;
  final List<String> lastNames;
}
